GENIE-MC/Generator

- src/Physics/HadronTransport/INukeNucleonCorr.cxx
When building the doxygen documentation, I currently get a "Undefined control sequence" error due to a typo ("\rhp" instead of "\rho") in the doxygen documentation for INukeNucleonCorr::mstar(). This pull request corrects the typo. Trailing whitespace has also been removed from a few lines of INukeNucleonCorr.cxx.
> Fix LaTeX typo in the doxygen documentation for INukeNucleonCorr::mstar()

- config/G18_10a/ModelConfiguration.xml
- config/G18_10b/ModelConfiguration.xml
- config/NievesQELCCPXSec.xml
As discussed with @dytman and @nusense today, the Nieves CCQE model uses the name "DipoleELFF" for its dipole form factor configuration instead of "Dipole," which is used by other models and is assumed to be present by some existing reweight calculators. This pull request corrects the discrepancy.
> Replace "DipoleELFF" with "Dipole" in configuration for the NievesQELCCPXSec model

- src/Framework/ParticleData/BaryonResUtils.cxx
If some tunes were made to exclusive cross sections for resonance with definite quantum numbers then it would be better to return to the previous resonance parameters.
> Return to resonance parameters according to PDG-2016

- src/Physics/QuasiElastic/XSection/NewQELXSec.cxx
- src/Physics/QuasiElastic/XSection/NewQELXSec.h
The NewQELXSec class fails to vary the hit nucleon radius during spline integration. This problem arises because the input Interaction object is copied twice, and the radius is updated in the first copy instead of the second copy used during numerical integration. This leads to an artificial suppression of the QE cross section near threshold for tunes using the local Fermi gas model. The problem occurs solely during spline integration, i.e., the radius is varied correctly in QELEventGenerator.
This pull request fixes the problem by changing NewQELXSec to vary the radius in the correct Interaction object.
> Fix radius issue in NewQELXSec

- src/Framework/Ntuple/LinkDef.h
- src/Framework/Ntuple/NtpMCTreeHeader.cxx
- src/Framework/Ntuple/NtpMCTreeHeader.h
- src/Framework/Ntuple/NtpWriter.cxx
- src/Framework/Ntuple/NtpWriter.h
- src/Framework/Utils/TuneId.h
Append '*' to tune name if custom sources are involved.  There is a high probability of false positives on this (for instance if GXMLPATH is used to specify the location of spline files, or alternative Messager configs).  To that end, record the tuneDir and customDirs -- even though files might have been relocated at least it gives some hint of what was involved.
> Tunename in ntpheader

- src/scripts/gcint/genie_setup.C
- src/scripts/gcint/loadincs.C
Slightly better detection of when something is wrong when the interpreter is loaded. No longer prints out a zero to screen every time interpreter is loaded
> make interpreter loading neater

- src/Apps/gEvPick.cxx
In the existing code, a copy of the accepted event record is created but never deleted. This eventually fills memory in cases where many events are accepted. The gEvPick app works just as well without copying the event record, so I made that change.
> Fix memory leak in the gEvPick app

- src/Apps/gAtmoEvGen.cxx
- src/Tools/Flux/GAtmoFlux.cxx
This commit updates gevgen_atmo to abort with an error if one of the flux files
fails to load when calling LoadFluxData(). I got bit by this where I
accidentally mistyped a single flux file and that flux failed to load, but
there was only a small warning but everything else continued to run.
I also updated LoadFluxData() to immediately abort if a single flux
file fails to load instead of continuing in order to make sure that the error
message about the file failing to load comes last.
I also fixed a small typo in gevgen_atmo.
I have tested this with a similar commit to version 2.12.8 but have only build tested the current pull request on master.
> abort with an error if LoadFluxData() fails

- src/Apps/gEvGen.cxx
Addresses a request from Jonathan Paley to explicitly document this option when running gevgen --help
> Add "--tune" option to gevgen help message

- src/Apps/gAtmoEvGen.cxx
This commit updates gevgen_atmo to automatically select the longitudinal and
transverse radii for the flux surface when using a ROOT geometry and if the two
radii are not specified on the command line. If this is the case, both are set
to the diagonal of the bounding box of the geometry.
I *believe* the diagonals of the bounding box should be large enough to correctly sample the neutrino interaction vertices assuming that the origin of the ROOT geometry is within the bounding box.
I have *not* extensively tested this. So far I have done some basic testing with a similar commit applied to version 2.12.8 and have just made sure that the pull request compiles on master so it should probably get tested more before being merged.
> automatically select flux surface radii for ROOT geometries

- src/make/Make.include
Starting with gcc 7, gcc -dumpversion only outputs the major version causing
syntax errors like the following when building:
awk: cmd. line:1: BEGIN { if(7>=4 && >0) print "YES"}
awk: cmd. line:1:                    ^ syntax error
The new version of gcc now works like the old version when passing
-dumpfullversion. This commit updates src/make/Make.include to use both
-dumpfullversion and -dumpversion since that appears to work for both old and new
gcc versions.
I noticed this on my machine which is running Fedora 27 which uses gcc 7.3.1.
The idea to pass both options came from this stackoverflow post: https://stackoverflow.com/questions/45168516/gcc-7-1-1-on-fedora-26-dumpversion-now-only-includes-major-version-by-default.
> update Makefile to pass both -dumpfullversion and -dumpversion to gcc

- src/Physics/Coherent/EventGen/COHPrimaryLeptonGenerator.cxx
- src/Physics/Common/PrimaryLeptonGenerator.cxx
- src/Physics/Common/PrimaryLeptonUtils.cxx
- src/Physics/Common/PrimaryLeptonUtils.h
- src/Physics/Multinucleon/EventGen/MECGenerator.cxx
- src/Physics/QuasiElastic/EventGen/QELEventGenerator.cxx
- src/Physics/QuasiElastic/EventGen/QELEventGeneratorSM.cxx
Move code to set the primary lepton polarization to a utility function. Set this polarization in the MECGenerator, QELEventGenerator, and QELEventGeneratorSM event record visitors.
> Ensure that the primary lepton polarization is set by all relevant generator classes

- config/G18_10a/G18_10a_02_11a/CommonParam.xml
- config/G18_10b/G18_10b_02_11a/CommonParam.xml
Fixing the missunderstanding with CMC naming
> Free nucleon paper

- .gitignore
- config/G18_01a/G18_01a_02_11a/CommonParam.xml
- config/G18_01a/G18_01a_02_11b/CommonParam.xml
- config/G18_01b/G18_01b_02_11a/CommonParam.xml
- config/G18_02a/G18_02a_02_11a/CommonParam.xml
- config/G18_02b/G18_02b_02_11a/CommonParam.xml
- config/G18_10a/G18_10a_02_11a/CommonParam.xml
Resolving issue with GXY_AB_02_11a tunes. Coping the KNO2Pythia XML block into the tune-specific CommonParam.xml files while leaving everything else the same
> Devel 02 11a config fix

- src/scripts/build/ext/build_pythia6.sh
With recent versions of gcc (at least on my system with gcc > 10.2) symbols are created in the BSS data section, whereas with old versions (tested with gcc 4.8) they are created as common. The linking of `pythia6_common_address` with `pydata` only works if symbols are created as common, otherwise the linker complains about multiple definitions.
Adding the flag `-fcommon` forces the symbols to be created as common even in modern compilers. Now it works on my system and with previous versions of gcc.
> added -fcommon flag to force common symbols

- src/Tools/Flux/GSimpleNtpFlux.cxx
- src/Tools/Flux/GSimpleNtpFlux.h
Addition of time variable for start of flux ray (to be filled by, say, dk2nu) representing time from proton-on-target to the flux window that is the start of the ray.
Pass this time along as part of X4 in flux driver mode with option, for backward compatibility, of ignoring it.
> Addition of start time of ray (in parallel to start position) and passing it on when used as flux driver

- src/Physics/QuasiElastic/XSection/QELUtils.cxx
- src/Physics/QuasiElastic/XSection/QELUtils.h
The effective energy transfer defined in Eq. (43) of the original Valencia model paper (https://arxiv.org/abs/nucl-th/0408005) may be recast in terms of a particular choice of an initial struck nucleon total energy (possibly off the mass shell). For EMQE and NCEL, the treatment leaves the nucleon on-shell. For CCQE, there is a modest correction to the on-shell value.
This pull request adds the Valencia binding energy "recipe" as an option to use when generating CCQE events. It lives alongside the others harmoniously, including the default "UseNuclearModel" option.
> Add Valencia-style binding energy treatment as an option for QE event generation

- config/G18_02a/G18_02a_03_320/AGKYLowW2019.xml
- config/G18_02a/G18_02a_03_320/CommonParam.xml
- config/G18_02a/G18_02a_03_320/Pythia6Hadro2019.xml
- config/G18_02a/G18_02a_03_320/Pythia8Hadro2019.xml
- config/G18_02a/G18_02a_03_330/AGKYLowW2019.xml
- config/G18_02a/G18_02a_03_330/CommonParam.xml
- config/G18_02a/G18_02a_03_330/Pythia6Hadro2019.xml
- config/G18_02a/G18_02a_03_330/Pythia8Hadro2019.xml
In this pull request, the different CMC containing the results from the hadronization paper are handled. So far I added the configurations for the G18_02a only.
> Adding Hadronization paper CMC

- config/HAIntranuke2018.xml
- src/Physics/HadronTransport/HAIntranuke.cxx
- src/Physics/HadronTransport/HAIntranuke2018.cxx
- src/Physics/HadronTransport/HNIntranuke2018.cxx
- src/Physics/HadronTransport/Intranuke.cxx
- src/Physics/HadronTransport/Intranuke.h
- src/Physics/HadronTransport/Intranuke2018.cxx
- src/Physics/HadronTransport/Intranuke2018.h
Adding a MFP parameter for Charged and Neutral pions. This adds coherence between the Frac Abs charged pions parameter and the MFP.
> adding different parameters for neutral and charged pion mean free path

- src/Physics/QuasiElastic/XSection/NievesQELCCPXSec.cxx
- src/Physics/QuasiElastic/XSection/NievesQELCCPXSec.h
I decided to implement it only for Nieves, as it is what we wanna use for the tuning. Changing it more globally using the QEUtils::BindHitNucleon function was difficult, as within that function, I had no access to the information on the final state particles, hence, I could not calculate q0Tilde. I wanted to have a QvalueShift that had a similar meaning for 1p1h and 2p2h interactions, as the shift on 2p2h should be 2 the shift in 1p1h interactions.
> adding Qvalue shift on q0Tilde

- src/Physics/Multinucleon/XSection/MECScaleVsW.cxx
The weight for events with W<0 is left to the default weight of 1. Because the default weight is configurable (fDefaultWeight), I decided to change this to 1 to avoid confusion.
> Fixing default behaviour

- src/Tools/Geometry/ROOTGeomAnalyzer.cxx
ROOT versions 6.16 through 6.24 would leave the in memory representation of a GDML file in mm rather than the long standing ROOT standard of cm.  Force the use of kRootUnits before TGeoManager::Import().
> force TGeoManager to use kRootUnits (cm)

- src/Framework/EventGen/EventGeneratorListAssembler.h
- src/Framework/EventGen/GMCJMonitor.h
- src/Framework/Interaction/Interaction.h
- src/Framework/Numerical/GSLUtils.h
- src/Framework/Utils/AppInit.h
- src/Framework/Utils/UnitUtils.h
- src/Physics/HadronTransport/HG4BertCascIntranuke.h
- src/Physics/HadronTransport/HINCLCascadeIntranuke.h
- src/Physics/PartonDistributions/LHAPDF5.h
- src/Physics/PartonDistributions/LHAPDF6.h
- src/Physics/Resonance/XSection/BostedChristyEMPXSec.h
- src/Physics/XSectionIntegration/GSLXSecFunc.h
Future versions of ROOT dictionary code will no longer include the line `namespace std {} using namespace std;`
Additionally the header order from a glob might be different
> Add forward declarations and using statements so that header order in dictionary creation doesn't matter

- src/Apps/gEvGen.cxx
- src/Apps/gEvGenDM.cxx
- src/Apps/gFNALExptEvGen.cxx
- src/Apps/gT2KEvGen.cxx
Histograms with variable bin widths are not properly sampled by TH1D::GetRandom() -- only by height not by area so re-fill any variable bin width histograms with contents*width before handing them to the flux driver.  This is conditional on ROOT_VERSION < 9.99.99 which can be changed if in the future the behavior is corrected.
> For applications using histogram fluxes account for deficiency in GetRandom() if variable bin widths

- src/Apps/gFNALExptEvGen.cxx
use TTree:CloneTree() to copy the metadata TTree to the output file (avoids warning messages)
> easier means of cloning metadata TTree

- src/scripts/gcint/genie_setup.C
I'm not sure what changed, but the use of "genie::RunOpt::Instance()" was failing with v3_02_00 and root v6_22_08 because it was seen an an incomplete class.  By pulling in the header the genie-as-a-super-root works again cleanly
> add #include RunOpt.h because otherwise treated as an incomplete class

- src/Physics/DeepInelastic/XSection/KNOTunedQPMDISPXSec.cxx
We noticed some double counting in electron scattering inclusive plots. This was due to a correction factor applied to fWcut. This correction  isn't needed as we are already calculating the cross sections above Wcut before merging them together. We can safely remove this additional correction factor. 
This pull request was discussed in the latest GENIE Tuning meeting (https://genie-docdb.pp.rl.ac.uk/cgi-bin/private/ShowDocument?docid=320)
> removing safety factor for Wcut

- src/Tools/Flux/GSimpleNtpFlux.h
short inline method was overlooked.
> implement SetIncludeVtxt() method

- src/Physics/HadronTransport/Makefile
- src/make/Make.include
newer versions of rootcling object to -p flags that using all of Geant4's cflags bring to the table.
> don't pass rootcling Geant4's non -I cflags

- src/Physics/BeamHNL/HNLBRCalculator.cxx
Majorana and Dirac decay widths for N4 --> v e mu were switched in BeamHNL/HNLBRCalculator.cxx
> BeamHNL bugfix in N4 --> v e mu mode Majorana vs Dirac

- config/GPRD18_10a/MECScaleVsW.xml
- config/GPRD18_10a/README.md
- config/GPRD18_10a/XSecLinearCombinations.xml
The readme was pointing out to the wrong experiment. The tunes were performed with MiniBooNE data
> Fix Nuclear tune README

- src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.cxx
Julia tested the updated SuSAv2 and co models with EM scattering and found an issue. We quickly traced this down to a silly typo when I was expanding the SuSA code to work for CRPA as well. This is now fixed.
> fixing typo

- src/Physics/QuasiElastic/XSection/NievesQELCCPXSec.cxx
There was a Scaling EM parameter for Nieves but this model doesn't support EM mode. I removed the parameter from the implementation
> removing EM parameter for Nieves. Model only for neutrinos

- src/Tools/Geometry/ROOTGeomAnalyzer.cxx
This is no longer necessarily an error condition due to changes in how ROOT v6.25.02 handles isomers. See https://github.com/root-project/root/pull/8556 for details.
> Remove fatal error when a TGeoMixture object reports a duplicate nuclear PDG code

- src/Framework/EventGen/GMCJDriver.cxx
Now, the maximum energy of the spline built inside the `GMCJDriver` is defined as the maximum of validity energy range for this generator. Sometimes there are cases when the splines are pre-calculated in a range whose maximum is lower than the maximum of the validity energy range. In such cases, the total cross section spline is incorrect at the highest energies and the generated events are skewed.
> Fix edge issue in GMCJDriver

- src/Physics/Resonance/XSection/BSKLNBaseRESPXSec2014.cxx
The new RES-EM Scaling parameter was not loaded in the BS xsec class. As a consequence, it was given a very small number, causing the xsec calculation to be always 0. This PR fixes this. I had a close look at the other processes. This behaviour is not observed, indicating the only problematic process was EMRES for the BS model.
> Addressing EM RES issue

- src/Physics/Resonance/XSection/BSKLNBaseRESPXSec2014.cxx
- src/Physics/Resonance/XSection/BSKLNBaseRESPXSec2014.h
1. EM factor wasn't calculated appropriately - fix it.
2. Due to the first, there is no need to keep sinus of Weinberg angle.
> Fix EM-XSec factor, delete unused variables in BSKLNRES model

- config/EventGenerator.xml
The diffractive scattering this is a process like $\nu_\mu + p \rightarrow \mu^- + \pi^+ + p$ and $\bar\nu_\mu + p \rightarrow \mu^+ + \pi^- + p$ (see e.g Phys. Rev. D 97 (2018) 032014 or Nucl. Phys. B 278 (1986) 61-77). The typical diffractive event looks like:
```
|------------------------------------------------------------------------------------------------------------------|
|GENIE GHEP Event Record [print level:   3]                                                                        |
|------------------------------------------------------------------------------------------------------------------|
| Idx |          Name | Ist |        PDG |   Mother  | Daughter  |      Px |      Py |      Pz |       E |      m  | 
|--------------------------------------------------------------- …
```
> Change configuration for  Diffractive event generator

- config/EventGeneratorListAssembler.xml
- src/Physics/NuclearDeExcitation/NucDeExcitationSim.cxx
IBD list has been added in config/EventGeneratorListAssembler.xml to select only this channel running the VLE tune
in src/Physics/NuclearDeExcitation/NucDeExcitationSim.cxx line 413, const has been added defining ns12
> add IBD list for VLE tune

- .gitmodules
- Makefile
- configure
- src/make/Make.include
Professor2 is not yet used directly inside Generator itself, but this
will be useful for the WIP reweight update. Since both comparison
and reweight package is going to be linked to  professor2. We are
putting professor2 as external code for GENIE.
The version selected is professor-2.4.1. The design of submodule 
system only allow specifying branch or commit. 
Checking out of submodules will be done automatically when 
user call `configure` with `--enable-professor2`.
> PROFRW - Move professor2 from reweight to GENIE

- configure
I'm working on a system (a Mac M1 with Root installed using the [Spack](https://spack.io) package manager) where the Root libraries are installed under `$ROOTSYS/lib/root`, not `$ROOTSYS/lib` so the original detection of whether or not Root was compiled with mathmore is not working. 
I'm proposing here a fix based on the `root-config` executable instead.
> configure: change detection of Root MathMore

- src/Framework/EventGen/HybridXSecAlgorithm.cxx
Ad hoc solution of problem with inappropriate kinematic phase space reported by @jtenavidal, so she can continue working. 
The reason of problem: it is intended for _LlewelynSmith_,  **but** also used by _Rosenbluth_.
A more thoughtful solution could be:
1. Specify in the configuration file the phase space appropriate for each algorithm.
2. Implement in RosenbluthPXSec the analog of method _LwlynSmithQELCCPXSec::FullDifferentialXSec_.
> Fix kinematic phase space issue in HybridXSecAlgorithm (due to RosenbluthPXSec)

- data/example/matrix/testmat.dat
- src/Framework/Algorithm/AlgConfigPool.cxx
- src/Framework/Algorithm/AlgConfigPool.h
- src/Framework/Algorithm/Algorithm.cxx
- src/Framework/Algorithm/Algorithm.h
- src/Framework/Algorithm/Algorithm.icc
Since a covariance matrix is needed when I implement the reweight method for Z expansion vector form factor model. Here is a solution to import the covariance matrix from xml configuration.  Covariance matrix can be imported from xml directly or from a plain text file. There are two example:
` <param type="mat-double" name="CCTEST0@CovarianceMatrix" importfile="false" rowdelim=";" coldelim=","> 2.0, 1.0, 2; 1.1, 2.1, 2; 1.1, 2.1, 2; 1.1, 2.1, 3.2 </param>`
`<param type="mat-double" name="CCTEST1@CovarianceMatrix" importfile="true"> /exp/uboone/app/users/liangliu/Genie/genie/Reweight/data/testmat.dat  </param>`
The matrix can be get by [GetParamMat()](https://github.com/LiangLiu212/Generator/blob/f5b1e0aed0fa88b623bb3f6c285f9a9a6dcd2d32/src/Framework/Algorithm/Algorithm.h#L197C1-L203C37)
> Add a Configuration of matrix in Genie

- src/scripts/production/python/FindGpvmFails.py
- src/scripts/production/python/eAScatteringGridSubmitter.py
This script is developed by @alons126 and I did some last checks. We need it as for electron jobs at the grid, in which we might run many parallel jobs, some of the parallel jobs might go on hold due to limited resources used by the finished jobs. In this case we end up with less events than expected and we need to re-run the events. This script facilitates the re-running of the events
> adding new script to help us address hold jobs which return no output

- src/Framework/Algorithm/AlgConfigPool.cxx
- src/Framework/EventGen/GMCJDriver.cxx
- src/Framework/EventGen/PathLengthList.cxx
- src/Framework/Messenger/Messenger.cxx
- src/Framework/Ntuple/NtpWriter.cxx
- src/Framework/Numerical/Spline.cxx
- src/Framework/Utils/XmlParserUtils.cxx
- src/Framework/Utils/XmlParserUtils.h
- src/Physics/Decay/BaryonResonanceDecayer.cxx
- src/Physics/Hadronization/Pythia6Hadro2019.cxx
- src/Physics/Multinucleon/EventGen/MECGenerator.cxx
- src/Physics/Multinucleon/XSection/EmpiricalMECPXSec2015.cxx
- src/Physics/NuclearState/FermiMomentumTablePool.cxx
- src/Tools/Flux/GNuMIFlux.cxx
This is a side-product when invegesting some memory leak with GENIE in JUNO (which turns out to be issues in certain ROOT version). But profiling of memory allocation and deallocation (`fsanitize=leak`) inside GENIE showed some memroy leak. I cleaned some of them (that happens multiple times).
Most issues are kind of equivalent to 
```cpp
int p = *(new int); // but the new is hidden in function call that not that obvious. 
```
Also, I add a function `TrimSpacesClean` next to `TrimSpaces` to clean memory allocated by `xmlNodeListGetString`.
> Fix some obvious memory leak

- src/Framework/Ntuple/LinkDef.h
- src/Framework/Ntuple/NtpMCEventRecord.cxx
This is related to a [long existing bug in ROOT](https://github.com/root-project/root/issues/16375), with related workaround in GENIE traced back to [this commit from Apr 2006](https://github.com/GENIE-MC/Generator/commit/64b7b4b759803785202961211342ff1295c98bae). But such workaround by manually calling the `Clean` method after each entry of event being processed is not possible with working with the latest ROOT's RDataFrame analysis framework like I did [in the reweighting testing code](https://github.com/karuboniru/Reweight/blob/professor_reweight/src/Apps/gRwProfTest.cxx).
The bug is that a class is being read from a ROOT file and: 
- the class contains a pointer to another object
- the root dict for the class is generated without a "+" in `#pragma link C++ class ClassName+;`.
Since …
> Workaround a memory leak with old ROOT IO

- README.md
- data/logo/genie_banner_long.txt
We had not yet updated the collaboration list to include Liang Liu (postdoc at Fermilab working with Steven G). This PR includes his name in both places where the authors appear in the repository.
> Add Liang Liu to long banner and README

- src/make/Make.include
Nobody knows why this `-lnsl` library was linked in, but it doesn't seem necessary any more and isn't available by default on AlmaLinux9 nodes.
> nsl library is no longer required

- src/scripts/gcint/loadlibs.C
- src/scripts/setup/genie-config
Add to genie-config new options --features and --has-<feature> (e.g. --has-pythia6)
Skip loading Pythia6 libraries in loadlibs.C when they aren't available
> feature enhance genie-config and don't load pythia6 libraries in loadlibs.C if not available 

- src/Physics/XSectionIntegration/GSLXSecFunc.cxx
Update to the DarkNeutrino module cross sections.
Applied a lower cut to the range of integration over E_DNu in order to correct the unphysical behaviour of the total cross-sections.
The cut corresponds to a Q^2(Max) < 1 GeV^2, above which the differential cross-sections are negligible.
> Constrained lower limit for EDnu integration.

- src/make/Make.include
`root-config --arch` returns `macosxarm64` on my new Fermilab-issued MacBook Pro, and this confuses the GENIE build system. Adding this as a possibility to `Make.include` builds fine with otherwise normal `macosx64` settings.
> Add handling of the macOS arm64 architecture to Make.include

- src/Physics/Resonance/EventGen/RESKinematicsGenerator.cxx
After some adjustments to the variables acceptance/rejection sampling for the RES calculator was using a couple years ago, when RES events were stored, the phase space variables used were not correctly stored in the event---instead the wrong set of variables were.  This PR fixes that oversight.
> correctly record the phase space used in RES calculator

- configure
Using root-config directly is more portable.
> Remove use of 'hash' to check for root-config in the configure script.
