src/Physics/HadronTransport/INukeHadroData2018.cxx, src/Physics/HadronTransport/INukeHadroData2018.h, src/scripts/setup/genie-config
I did not take the liberty to change the interface, only fixed some memory leaks.
=> Fix memory leaks

config/Messenger.xml, config/Messenger_inuke_verbose.xml, config/Messenger_laconic.xml, config/Messenger_rambling.xml, config/Messenger_whisper.xml
Define priority levels for Smith-Moniz message streams.
=> define priority levels for Smith-Moniz message streams

config/GSystUncertaintyTable.xml, config/master_config.xml
This is a companion pull request to GENIE-MC/Reweight#7. The two should be tested and merged at the same time. This pull request only modifies the XML configuration in Generator. All code changes are in Reweight.
=> Add an XML configuration for the new GSystUncertaintyTable algorithm in Reweight

config/Messenger.xml, config/Messenger_inuke_verbose.xml, config/Messenger_rambling.xml, config/Messenger_whisper.xml, src/Apps/gEvGen.cxx, src/Framework/EventGen/GMCJDriver.cxx, src/Framework/GHEP/GHepUtils.cxx
This pull request resolves issues #6, #20, #28, and #84.
=> Simple fixes

config/G18_01a/G18_01a_02_11a/CommonParam.xml, config/G18_01b/G18_01b_02_11a/CommonParam.xml, config/G18_02a/G18_02a_02_11a/CommonParam.xml, config/G18_02b/G18_02b_02_11a/CommonParam.xml, config/G18_10a/G18_10a_02_11a/CommonParam.xml, config/G18_10b/G18_10b_02_11a/CommonParam.xml
Updating the xml files to be consistent with the paper results. This should be included in version 3.2
=> Free nucleon paper

config/G18_10b/G18_10b_02_11a/CommonParam.xml, config/G18_10b/G18_10b_02_11b/CommonParam.xml
=> Free nucleon update g1810b

src/Apps/gEvPick.cxx
Added two additional initial-state 'topology' options for completeness.
Changed two FATAL labels to NOTICE. 
Added additional printout to the end of the script.
=> Additional tweaks to the interaction-based gevPick update.

src/Physics/Decay/DarkSectorDecayer.cxx
Switch to using a vector rather than a C-style array to store the particle masses for the DarkSectorDecayer. This resolves a compilation error for GCC 4.8.5 and manages memory in a safer way.
=> Fix compilation problem for the DarkSectorDecayer

config/BostedChristyEMPXSec.xml, config/master_config.xml, src/Physics/Resonance/XSection/BostedChristyEMPXSec.cxx, src/Physics/Resonance/XSection/BostedChristyEMPXSec.h, src/Physics/Resonance/XSection/LinkDef.h
The fit of electron scattering data in the resonance region for proton, deuterium and heavier nuclei.
=> Bosted-Christy fit

config/QvalueShifter.xml, config/master_config.xml, src/Physics/Common/LinkDef.h, src/Physics/Common/QvalueShifter.cxx, src/Physics/Common/QvalueShifter.h, src/Physics/Multinucleon/XSection/NievesSimoVacasMECPXSec2016.cxx, src/Physics/Multinucleon/XSection/NievesSimoVacasMECPXSec2016.h, src/Physics/Multinucleon/XSection/SuSAv2MECPXSec.cxx, src/Physics/Multinucleon/XSection/SuSAv2MECPXSec.h, src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.cxx, src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.h
New implementation of the Qvalue shift
=> Qvalue shift new

src/Physics/Multinucleon/EventGen/MECGenerator.h
=> remove unimplmented declaration

src/Apps/gAtmoEvGen.cxx, src/Apps/gEvGen.cxx, src/Apps/gEvGenDM.cxx, src/Apps/gEvGenHadronNucleus.cxx, src/Apps/gEvGenLArDM.cxx, src/Apps/gFNALExptEvGen.cxx, src/Apps/gNNBarOscEvGen.cxx, src/Apps/gNeutralHeavyLeptonEvGen.cxx, src/Apps/gNucleonDecayEvGen.cxx, src/Apps/gT2KEvGen.cxx, src/Framework/Ntuple/NtpMCTreeHeader.cxx, src/Framework/Ntuple/NtpMCTreeHeader.h, src/Framework/Ntuple/NtpWriter.cxx, src/Framework/Ntuple/NtpWriter.h
This PR extends the NtpHeader to store the seed used for the run
=> Add seed to ghep file

src/Physics/Multinucleon/XSection/SuSAv2MECPXSec.cxx, src/Physics/Multinucleon/XSection/SuSAv2MECPXSec.h, src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.cxx
Pull request to consider Qvalue shifts in susa
=> Qvalue susa

src/Apps/Makefile, src/Apps/gConfigDump.cxx
print out algorithm configurations and Common* configs in Registry format
list which file is being used for Common* configs
=> new App for dumping configuration in (semi)human readable form

src/Physics/HadronTransport/INukeUtils2018.cxx, src/Physics/HadronTransport/INukeUtils2018.h, src/Physics/HadronTransport/Intranuke2018.cxx, src/Physics/HadronTransport/Intranuke2018.h
Implements updates needed to fix reweighting of FSIs in the hA2018 model. A related pull request in Reweight should be merged at the same time as this one.
=> FSI reweighting fixes for v3.2 (Generator)

config/DipoleELFormFactorsModel.xml, config/EmpiricalMECPXSec2015.xml, config/GSystUncertaintyTable.xml, config/NewQELXSec.xml, config/QELXSec.xml, src/Framework/Utils/KineUtils.cxx, src/Physics/HadronTransport/INukeUtils2018.cxx, src/Physics/HadronTransport/INukeUtils2018.h, src/Physics/HadronTransport/Intranuke2018.cxx, src/Physics/HadronTransport/Intranuke2018.h, src/Physics/Multinucleon/EventGen/MECGenerator.cxx, src/Physics/Multinucleon/XSection/EmpiricalMECPXSec2015.cxx, src/Physics/Multinucleon/XSection/EmpiricalMECPXSec2015.h, src/Physics/Multinucleon/XSection/NievesSimoVacasMECPXSec2016.cxx, src/Physics/QuasiElastic/XSection/DipoleELFormFactorsModel.cxx, src/Physics/QuasiElastic/XSection/NewQELXSec.cxx, src/Physics/QuasiElastic/XSection/NewQELXSec.h, src/Physics/QuasiElastic/XSection/NievesQELCCPXSec.cxx, src/Physics/QuasiElastic/XSection/NievesQELCCPXSec.h
A corresponding branch for Reweight also exists.
=> Extra reweighting fixes/additions for v3.2

src/Framework/Interaction/SppChannel.h
fix signs of Clebsch–Gordan coefficients according to PDG
=> fix signs of Clebsch–Gordan coefficients according to PDG

src/Framework/Interaction/SppChannel.h
=> fix cb signs

src/Tools/EvtLib/EventLibraryInterface.h, src/Tools/EvtLib/Key.h
includes that strictly should have been there all along
=> add some missing headers that need be there if dictionary creation order is arbitrary 

config/MKSPPXSec.xml, src/Physics/Resonance/XSection/MKSPPXSec.cxx
change default config parameters
=> Mk single pion

src/scripts/production/python/README.md, src/scripts/production/python/XMLGridSubmitter.py, src/scripts/production/python/eAScatteringGridSubmitter.py, src/scripts/production/python/event_generation/eScatteringGenCommands.py, src/scripts/production/python/event_generation/nuScatteringGenCommands.py, src/scripts/production/python/setup_GENIE.sh, src/scripts/production/python/vAScatteringGridSubmitter.py, src/scripts/production/python/xsec_splines/FNALGridUtils.py, src/scripts/production/python/xsec_splines/GroupSplineCommands.py, src/scripts/production/python/xsec_splines/vASplineCommands.py, src/scripts/production/python/xsec_splines/vNSplineCommands.py
Adding new features to the python scripts. Tested the whole chain.
=> Running neutrino jobs at FNAL

src/scripts/production/python/xsec_splines/FNALGridUtils.py
The jobsubmission command doesn't allow decimals. This is fixed now
=> jobsub_lite update

src/Physics/Hadronization/AGKYLowW2019.cxx
[Comparison plots](https://github.com/GENIE-MC/Generator/files/10931086/slides.pdf)
This should fix https://github.com/GENIE-MC/Generator/issues/226 if I understood the code correctly.
=> Fix a boost in AGKYLowW2019 (#226)

src/Physics/BeamHNL/HNLBRCalculator.cxx
See JHEP 10 (2007) 015, Appdx. A
=> Addition of "flavour flipped" diagram to N --> v e mu mode

src/scripts/production/python/README.md, src/scripts/production/python/XMLGridSubmitter.py, src/scripts/production/python/eAScatteringGridSubmitter.py, src/scripts/production/python/event_generation/eScatteringGenCommands.py, src/scripts/production/python/event_generation/nuScatteringGenCommands.py, src/scripts/production/python/setup_GENIE.sh, src/scripts/production/python/vAScatteringGridSubmitter.py, src/scripts/production/python/xsec_splines/FNALGridUtils.py, src/scripts/production/python/xsec_splines/GroupSplineCommands.py
This is a place holder for further developments on the FNAL scripts 
Problems adressed:
- setting a minimum number of events of 400k for e scattering to avoid high number of jobs runing
- Fixing a bug : GB -> MB for disk space
=> FNAL Scripts Update

src/scripts/production/batch/xsec_splines/vA_spline_generator.pl, src/scripts/production/batch/xsec_splines/vN_spline_generator.pl
removing priority line for lyonslurm farm
=> removing priority line

src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.cxx
I added a bug in Susa QEL event generator due to a merge conflict... This fixes it.
=> fixing bug. Info process not defined

src/scripts/production/python/eAScatteringGridSubmitter.py, src/scripts/production/python/event_generation/eFluxScatteringGenCommands.py, src/scripts/production/python/event_generation/eScatteringGenCommands.py, src/scripts/production/python/event_generation/hadronScatteringGenCommands.py, src/scripts/production/python/event_generation/nuScatteringGenCommands.py, src/scripts/production/python/hadronAScatteringGridSubmitter.py, src/scripts/production/python/vAScatteringGridSubmitter.py, src/scripts/production/python/xsec_splines/FNALGridUtils.py
Adding scripts to run h-A events
=> FNAL Scripts

config/BergerSehgalRESPXSec2014.xml, config/ReinSehgalRESPXSec.xml, config/ReinSehgalRESXSecFast.xml
This addresses https://github.com/GENIE-MC/Generator/issues/347
=> Optimisation of Integration method for EM RES

config/NucBindEnergyAggregator.xml, src/Physics/HadronTransport/NucBindEnergyAggregator.cxx
The generated events with four modules are attached.
[HAIntranuke2018.txt](https://github.com/GENIE-MC/Generator/files/13426806/HAIntranuke2018.txt)
[HG4BertCascIntranuke.txt](https://github.com/GENIE-MC/Generator/files/13426807/HG4BertCascIntranuke.txt)
[HINCLCascadeIntranuke.txt](https://github.com/GENIE-MC/Generator/files/13426808/HINCLCascadeIntranuke.txt)
[HNIntranuke2018.txt](https://github.com/GENIE-MC/Generator/files/13426809/HNIntranuke2018.txt)
=> restore functionality of NucBindEnergyAggregator

config/GEM21_11c/CommonParam.xml, config/GEM21_11d/CommonParam.xml
https://github.com/GENIE-MC/Generator/issues/378
=> Addressing issue 378

src/scripts/production/python/xsec_splines/GroupSplineCommands.py
=> removing conversion as it leads to problematic cases

src/Tools/Flux/GSimpleNtpFlux.cxx
The `GSimpleNtpFlux` class allows the user to shift the starting z coordinate for a neutrino ray off of the flux window. When this is done, the other spatial coordinates are updated accordingly, but the time is set to zero.
The failure to set a consistent shift to the starting time appears to be the cause of a problem recently encountered when generating dirt samples in SBND (https://github.com/SBNSoftware/sbndcode/issues/410). This pull request implements the missing time shift to resolve the problem.
=> Implement time shift in GSimpleNtpFlux::MoveToZ0()

config/SuSAv2QELHadronTensorModel.xml, config/SuSAv2QELPXSec.xml, src/Physics/HadronTensors/HadronTensorI.h, src/Physics/HadronTensors/TabulatedHadronTensorModelI.cxx, src/Physics/HadronTensors/TabulatedHadronTensorModelI.h, src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.cxx
The existing implementation of the SuSAv2 EM QE model doesn't distinguish between struck protons and neutrons, leading to an incorrect equal cross section for p and n knockout. Liang Liu (@LiangLiu212) has added tensors from Guillermo Megias separated by isospin, together with code to handle them correctly for cross section calculations and event generation.
=> Add SuSAv2 EM QE hadron tensors separated by hit nucleon isospin
